### ISSUE TITLE
Handling device permissions: 'Microphone consent is no given'

### ISSUE THREAD

**Issue by alpe88** [speechly/speech-recognition-polyfill#6]
### To Reproduce
1. Implement a basic (or any) speech button in a react app
2. Click the button
3. After the permission browser pops up, click the `x` to close it without approving or denying the request
4. Observe error: `Unhandled Rejection (Error): Microphone consent is no given` in `./node_modules/@speechly/browser-client/microphone/types.js`

### Expected behaviour
I couldn't find any documentation on the recommended way to handle this error. I've tried some of the typical ways but nothing worked, apologies if this is not the appropriate forum for this.

### Environment

- Platform: [e.g. Mobile, Desktop, React Native]: React Web App
- OS: [e.g. iOS]: macOs
- Browser [e.g. chrome, safari]: chrome, latest
- Package version [e.g. 1.2.3]: latest

**Comment by JamesBrill** [comment]
Hi @alpe88 Thanks for raising this issue! You're absolutely right that there should be a way to gracefully handle the case where the user does not give the browser permission to use the microphone. In such a case, you may want your React app to fallback to a text-based interface or display a message like "You need to enable the microphone for voice features to work".

There are two things missing currently (both because of my oversight):
* In this library, there is no documentation explaining what to do when no permission is given. If you are using this library without the `react-speech-recognition` sister library, you could handle these errors by wrapping `start` in an error handler:
```
  const startListening = async () => {
    try {
      await speechRecognition.start();
    } catch (e) {
      // Fallback behaviour
    }
  }
```
* I suspect you are using this library with `react-speech-recognition` (this is recommended). Unfortunately, `react-speech-recognition` assumes that the polyfill's `start` method is synchronous. In this polyfill, it is asynchronous (a slight deviation from the W3C spec) due to the underlying Speechly client being asynchronous. As a result, `react-speech-recognition` fails to handle any errors thrown by the Speechly `start` method. I shall need to update `react-speech-recognition` to handle this case - this shouldn't affect its interface as `startListening` is already an asynchronous method. Once that's in place, I will document a solution like:
```
  const startListening = async () => {
    try {
      await SpeechRecognition.startListening();
    } catch (e) {
      // Fallback behaviour
    }
  }
```

You may be wondering what action you can take to solve this until I've applied the above fixes. It's not great, but the best you can do is to try to catch the unhandled rejected promise and cancel it (note that your React app will still crash locally due to how Webpack handles these errors, but it should be fine in a production environment):
```
window.addEventListener('unhandledrejection', (event) => {
  if (event.reason.message === 'Microphone consent is no given') {
    event.preventDefault();
    // Fallback behaviour
  }
});
```

I'll post back here once I've applied the fixes - I'll aim to get them done within the next week.

**Comment by JamesBrill** [comment]
Hi @alpe88 I've just released version 3.9.0 of `react-speech-recognition` (details [here](https://github.com/JamesBrill/react-speech-recognition/releases/tag/v3.9.0)). This introduces a new state emitted from the `useSpeechRecognition` hook: `isMicrophoneAvailable`. If this becomes `false`, it means that the user has denied access to the microphone. There should be no unhandled errors any more. In this case, you can render some suitable fallback content. So you just need something like:
```
  if (!isMicrophoneAvailable) {
    return <span>Please allow access to the microphone</span>
  }
```

If you aren't using `react-speech-recognition`, you still have the first solution proposed in my previous post. I'm also going to look into tweaking how this polyfill handles errors - it should probably be emitting them via the `onerror` callback rather than throwing an error.

Let me know how this worked for you.

**Comment by alpe88** [comment]
Thanks for this. Seeing one issue though, when permissions are set to `Ask for ...` `isMicrophoneAvailable` is `true`. 

I'm not sure what would be a better way to present the initial state when the microphone is neither available nor unavailable (because the permissions haven't been set).

Thanks!

**Comment by JamesBrill** [comment]
I think that when the permissions are unknown ("Ask"), `true` is a sensible default for `isMicrophoneAvailable`. If it was initially `false`, then consumer apps would disable their voice features and prevent the browser from having a chance to ask for permission in the first place - the user would never see the voice input and the permission for that domain would forever remain "Ask". So I'd say it's better to be "optimistic" and assume that if the user chooses to interact with the voice input to trigger the permissions dialog, they'll most likely select "Allow" (admittedly, I don't have any data on this).

However, I agree that there could be a better initial state for the "Block" case where the browser knows upfront that microphone permissions have been denied previously. I can imagine it being jarring to click on the voice input and then have the consumer app immediately hide it without the permissions dialog appearing in between.

There is a potential solution for this that I can look into, which is the `navigator.permissions` API. It doesn't have widespread [browser support](https://caniuse.com/?search=navigator.permissions) just yet, but where it's available I can use it to set the initial state to `false` for users that have set their permission to "Block".

**Comment by alpe88** [comment]
Thanks for working through this with me. I think we can close.

**Comment by JamesBrill** [comment]
Great! Just an FYI - we just released a new version of this library that supports an `onerror` callback. If you ever use this polyfill without `react-speech-recognition`, that is one option for handling errors. This is documented [here](https://github.com/speechly/speech-recognition-polyfill#handling-errors).
